Recognize UltraVnc and TightVNC server by security type
LibVNC/libvncserver pull request #506
Opened 2022-03-15 12:20 UTC by badda71

2022-03-15 13:10 UTC, badda71 commented
this PR fixes https://github.com/LibVNC/libvncserver/issues/505

2022-03-15 19:43 UTC, bk138 requested changes

2022-03-15 19:43 UTC, bk138 commented on libvncclient/rfbproto.c
> -  /* UltraVNC uses minor codes 4 and 6 for the server */
Those should be left as-is for compat with older servers.

2022-03-15 19:43 UTC, bk138 commented on libvncclient/rfbproto.c
> -
Please don't add unrelated whitespace.

2022-03-16 08:30 UTC, merged

2022-03-16 08:31 UTC, bk138 commented
Looks good, thanks for the contribution!