libvncclient: using gnutls_handshake_set_timeout()
LibVNC/libvncserver pull request #531
Opened 2022-07-19 09:17 UTC by mdevaev

Following #525

Removed sleep, using `gnutls_handshake_set_timeout()` and `gnutls_system_recv_timeout()`. It's working since GNUTLS 3.4.0 (released 2015-04-08).

Found a solution here: https://github.com/gnutls/gnutls/blob/857543cc24114431dd5dde0e83c2c44b9b7e6050/lib/system/fastopen.c#L167

Also a loop without sleep seems to be the regular way to use GNUTLS according to github.

2022-08-04 10:21 UTC, bk138 commented
@mdevaev That looks reasonable, but why not reap the rewards and remove the busy wait in tls_gnutls.c?

2022-08-04 12:05 UTC, mdevaev commented
What do you mean?

2022-08-04 13:55 UTC, mdevaev commented
As far as I understood from the documentation and examples, there really should be a loop here, because some errors may be non-fatal and it is recommended to just try handshake again.

2022-08-04 13:58 UTC, mdevaev commented
Yes, you're right. Check it please now.

2022-08-04 18:06 UTC, bk138 requested changes
Yeah, you were right, a while loop is more suited in that case but the timeout was OK to go.

Two more things I'd like to request:

* you can remove the [ifdef WIN32 starting in line 25](https://github.com/LibVNC/libvncserver/blob/540d4eaefae32b942fe305852422a92669113064/libvncclient/tls_gnutls.c#L25-L28), there is no sleep() in here anymore
* You mentioned support for this starts with a certain GnuTLS version. Please codify this in https://github.com/LibVNC/libvncserver/blob/540d4eaefae32b942fe305852422a92669113064/CMakeLists.txt#L148

2022-08-04 21:42 UTC, mdevaev commented
Done, check it plz

2022-08-05 10:44 UTC, merged

2022-08-05 10:45 UTC, bk138 commented
Thanks, it's a pleasure working with you.

2022-08-05 11:42 UTC, mdevaev commented
Thank you!)